Moved mkdir -vp in scripts/packaging.

diff --git a/scripts/packaging b/scripts/packaging
--- a/scripts/packaging
+++ b/scripts/packaging
@@ -4,6 +4,8 @@
 
 set -e
 
+mkdir -vp ${DEBIAN} ${SERVICE} ${APP} ${DOC} ${BLOCKADE}
+
 CHANGELOG=$(cat changelog)
 
 COMMIT=$(cat .git/COMMIT_EDITMSG)
@@ -20,37 +22,30 @@ ${NAME_VERSION} (${VERSION}) ubuntu; urgency=medium
 ${CHANGELOG}
 EOF
 
-# Create package directories.
-if ! mkdir -vp ${DEBIAN} ${SERVICE} ${APP} ${DOC} ${BLOCKADE} ; then
-	echo "Error: unable to create directories"
-	exit 1
+cp -f debian/changelog changelog
+
+# Aviod using cp to copy the main script because the version needs
+# to be set.
+sed "22iVERSION=${VERSION}" scr/blockade > ${APP}/blockade
+
+if ! cp -vf scr/blockade-hosts-update.* ${SERVICE}/ ; then
+	echo "Error: missing" && exit 1
 else
+	cp -vf scr/doc/* ${BLOCKADE}/
 
-	# Aviod using cp to copy the main script because the version needs
-	# to be set.
-	sed "22iVERSION=${VERSION}" scr/blockade > ${APP}/blockade
-
-	if ! cp -vf scr/blockade-hosts-update.* ${SERVICE}/ ; then
-		echo "Error: missing" && exit 1
+	# Copy and conpress changelog.
+	if ! cp -vf debian/changelog copyright ${DOC}/ ; then
+		echo "Missing: ${DOC} && ${SERVICE}" && exit 1
 	else
-		cp -vf scr/doc/* ${BLOCKADE}/
-
-		# Copy and conpress changelog.
-		if ! cp -vf debian/changelog copyright ${DOC}/ ; then
-			echo "Missing: ${DOC} && ${SERVICE}" && exit 1
-		else
-			if ! gzip -9 -vf ${DOC}/changelog ; then
-				echo "Error" && exit 1
-			fi
+		if ! gzip -9 -vf ${DOC}/changelog ; then
+			echo "Error" && exit 1
 		fi
+	fi
 
-
-		if ! cp -vf scr/postinst ${DEBIAN}/postinst ; then
-			echo "Missing: installer" && exit 1
-		else
-			chmod a+x ${DEBIAN}/postinst
-		fi
-
+	if ! cp -vf scr/postinst ${DEBIAN}/postinst ; then
+		echo "Missing: installer" && exit 1
+	else
+		chmod a+x ${DEBIAN}/postinst
 	fi
 
 fi
